# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ALAN.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 850)
        MainWindow.setMaximumSize(QtCore.QSize(650, 850))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(650, 850))
        self.centralwidget.setObjectName("centralwidget")
        self.logo_container = QtWidgets.QFrame(self.centralwidget)
        self.logo_container.setGeometry(QtCore.QRect(0, 0, 650, 150))
        self.logo_container.setMaximumSize(QtCore.QSize(650, 150))
        self.logo_container.setStyleSheet("background-color:rgb(40, 40, 39);")
        self.logo_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_container.setObjectName("logo_container")
        self.bot_logo = QtWidgets.QLabel(self.logo_container)
        self.bot_logo.setGeometry(QtCore.QRect(230, 0, 191, 141))
        self.bot_logo.setMaximumSize(QtCore.QSize(650, 150))
        self.bot_logo.setText("")
        self.bot_logo.setPixmap(QtGui.QPixmap("icon2.jpeg"))
        self.bot_logo.setScaledContents(True)
        self.bot_logo.setObjectName("bot_logo")
        self.display_container = QtWidgets.QFrame(self.centralwidget)
        self.display_container.setGeometry(QtCore.QRect(0, 150, 650, 630))
        self.display_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.display_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.display_container.setObjectName("display_container")
        self.terminal = QtWidgets.QTextBrowser(self.display_container)
        self.terminal.setGeometry(QtCore.QRect(0, 0, 650, 630))
        self.terminal.setStyleSheet("background-color:rgb(102,220,220);\n"
"color:white;font-size:16pt")
        self.terminal.setObjectName("terminal")
        self.bottom_container = QtWidgets.QFrame(self.centralwidget)
        self.bottom_container.setGeometry(QtCore.QRect(0, 780, 650, 70))
        self.bottom_container.setStyleSheet("background-color:rgb(40, 40, 39);\n"
"color:rgb(255, 255, 255);\n"
"font: 75 16pt \"DejaVu Sans\";")
        self.bottom_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_container.setObjectName("bottom_container")
        self.time_browser = QtWidgets.QTextBrowser(self.bottom_container)
        self.time_browser.setGeometry(QtCore.QRect(0, 30, 200, 40))
        self.time_browser.setStyleSheet("\n"
"border-radius:None;")
        self.time_browser.setObjectName("time_browser")
        self.start_button = QtWidgets.QPushButton(self.bottom_container)
        self.start_button.setGeometry(QtCore.QRect(580, 0, 60, 60))
        self.start_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("mic2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start_button.setIcon(icon)
        self.start_button.setIconSize(QtCore.QSize(60, 60))
        self.start_button.setObjectName("start_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ALAN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
